app = "mp3-http-proxy"

[http_service]
  internal_port = 8000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.ports]]
    port = 80
    handlers = ["http"]   # không ép HTTPS

  [[http_service.ports]]
    port = 443
    handlers = ["tls", "http"]
